---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: /src/k8s.io/helm

steps:
- name: build
  pull: default
  image: golang:1.10
  commands:
  - ./.circleci/bootstrap.sh
  - make test-unit
  - make build-cross APP=helm
  - make build-cross APP=tiller
  - make build-cross APP=rudder
  - mv ./_dist/linux-arm64/helm ./_dist/linux-arm64/helm-arm64
  - mv ./_dist/linux-arm64/tiller ./_dist/linux-arm64/tiller-arm64
  - mv ./_dist/linux-arm64/rudder ./_dist/linux-arm64/rudder-arm64
  environment:
    PROJECT_NAME: "\"kubernetes-helm\""
    TARGETS: linux/amd64 linux/arm64

- name: publish-github-rc
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/*"
    - _dist/linux-amd64/*
    - _dist/linux-arm64/*
    prerelease: true
  when:
    event:
    - tag
    ref:
    - "refs/tags/*rc*"
    - refs/heads/rancher

- name: github_binary_release
  pull: default
  image: plugins/github-release
  settings:
    checksum:
    - sha256
    files:
    - "bin/*"
    - _dist/linux-amd64/*
    - _dist/linux-arm64/*
    api_key:
      from_secret: github_token
  when:
    event:
    - tag
    ref:
      exclude:
      - "refs/tags/*rc*"
